notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - oicr:S9k4EowgQv9AnbCfEZHSzCsg
sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
install:
- docker version
- pip2.7 install --user cwl-runner cwltool==1.0.20160108200940 schema-salad==1.4.20160108200836 avro==1.7.7
- docker pull commonworkflowlanguage/nodejs-engine
before_script:
- psql -c "create user dockstore with password 'dockstore' createdb;" -U postgres
- psql -c "ALTER USER dockstore WITH superuser;" -U postgres
- psql -c 'create database webservice_test with owner = dockstore;' -U postgres
- export PATH=$PATH:$PWD/dockstore-client/target
script: mvn -B clean install -DskipITs=false -Pconfidential-tests
after_success:
- mvn -B clean -DskipITs=false cobertura:cobertura cobertura:cobertura-integration-test
  coveralls:report
before_install:
- openssl aes-256-cbc -K $encrypted_3622126f1fe3_key -iv $encrypted_3622126f1fe3_iv
  -in dockstore-integration-testing/src/test/resources/secrets.tar.enc -out dockstore-integration-testing/src/test/resources/secrets.tar -d
- tar xvf dockstore-integration-testing/src/test/resources/secrets.tar
